[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "mainframe-orchestra>=0.0.23",
    "pdfplumber>=0.11.5",
    "pypdf2>=3.0.1",
]
